### ISSUE TITLE
What should I do next after downloading binary file?

### ISSUE THREAD

**Issue by vietluu-collab** [josephburnett/jd#53]
Hi can I ask what should I do after downloading jd-amd64-windows.exe file? Thank you

**Comment by vietluu-collab** [comment]
@josephburnett can you please tell me the steps I should do after downloading the window binary file? Thank you

**Comment by josephburnett** [comment]
The binary file is meant to use on the command line. So when you're using cmd.exe or powershell or whatever you use in Windows, just run the binary and it will print out help by default. 

If you want to use the web UI locally, you can also provide the `-port` parameter and it will run the UI on your machine so you can copy/paste in diffs. Although this isn't very different from opening http://play.jd-tool.io/ because the UI runs entirely in the browser so your data never leaves your machine. The only difference is the local UI can be used when offline.

Does that answer your question? Let me know if you have anymore trouble or confusion around how to use jd.
