### ISSUE TITLE
install instructions out of date

### ISSUE THREAD

**Issue by mark-pictor-csec** [josephburnett/jd#67]
Using the latest release, 1.7.1:

Among the install options, the readme lists
> * run `go install github.com/josephburnett/jd@latest`,

however when I do that and then run `jd -port nnnn` I get
```
the web UI wasn't include in this build: use `make release` to include it
```
the `release` target does not exist. Looks like this message could be updated to say `make build`.

Making the full functionality available with `go install` would be nice but I'm guessing that just isn't feasible as long as wasm is involved.

**Comment by josephburnett** [comment]
Thanks @mark-pictor-csec for pointing that out! I've updated the instructions: https://github.com/josephburnett/jd/commit/cf8d02597f7569597407305a3b0146d21449d416

The WASM isn't checked into the source code because it's derived from the Go lib. And there isn't a hook available with `go install` to generate it. So I don't know of a way to provide it through that method. But all the others (release binary, docker image, etc... should have it).
